require:
  - ../lib/rubocop/cop/dry/unused_import.rb

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Dry/UnusedImport:
  Enabled: true
  InjectorName: 'AutoInject'