require:
  - rubocop_dry_import

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Dry/UnusedImport:
  Enabled: true
  InjectorName: 'AutoInject'